version: 2

sources:
  - name: jaffle_shop
    description: A sample data source for the jaffle_shop project.
    database: DBT_DEMO  # Explicitly set the database
    schema: jaffle_shop  # Explicitly set the schema
    tables:
      - name: customers
        description: One record per customer.
      - name: orders
        description: One record per order. Includes cancelled and deleted orders.
